### PR TITLE
Add some exploratory plots

### PR DESCRIPTION
**Pull request by kferris10**
I've also added an index.html file so we can share our results more easily.  Right now, it's just some exploratory plots that I'm using to practice with htmlwidgets

### CODE REVIEW

**Comment by mdlerch** [comment]
Do you want this to go into master or gh-pages?

**Comment by kferris10** [comment]
Um...I meant the gh-pages branch.

But what do you think?

**Comment by mdlerch** [comment]
I'm merging it in.  We can move things around later if desired.  As long as we can look at kferris10.github.io/forest_cover, there's really no need to also have mdlerch.github.io/forest_cover available as well.

**Comment by kferris10** [comment]
Good point.  What do you think of the data?

**Comment by mdlerch** [comment]
Playing around with the fits and such I think we need to figure out how 
to differentiate cover type 1 and cover type 2.  That seems to be the 
place where the models are most confused.

**Pull request merged**
